Numpy practice

In [16]:
import numpy as np

array_one = np.arange(1,101)

matrix_10 = array_one.reshape(10,10)
matrix_10

array_mean = array_one.mean()
array_mean

array_median = np.median(array_one)
array_median

array_variance = array_one.var()
array_variance

even_numbers = array_one[array_one % 2 == 0]
even_numbers


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [24]:
matrix_5 = np.random.rand(5,5)
matrix_5

#The normal function generates random numbers that follow a "normal distribution"
normal_dist = np.random.normal(loc=0, scale=1, size=1000)
normal_dist
dist_mean=normal_dist.mean()
dist_variance=normal_dist.var()
dist_std=normal_dist.std()
dist_std

1.0197550024605204

In [38]:
dice_one = np.random.randint(1,7,size=1000)
dice_two = np.random.randint(1,7,size=1000)

sum_dice = dice_one + dice_two

probability = np.sum(sum_dice > 7) / len(sum_dice)
probability


0.411

In [42]:
matrix_one = np.random.randint(1, 7, size=(3,3))
matrix_two = np.random.randint(1, 7, size=(3,3))
print(matrix_one)
print(matrix_two)
product = np.dot(matrix_one, matrix_two)
print(product)

deter_matrix = np.linalg.det(matrix_one)
inv_matrix = np.linalg.inv(matrix_one)
print(deter_matrix)
print(inv_matrix)


[[5 3 1]
 [3 6 3]
 [5 1 5]]
[[4 3 1]
 [3 1 6]
 [5 4 4]]
[[34 22 27]
 [45 27 51]
 [48 36 31]]
107.99999999999993
[[ 2.50000000e-01 -1.29629630e-01  2.77777778e-02]
 [-2.64338815e-17  1.85185185e-01 -1.11111111e-01]
 [-2.50000000e-01  9.25925926e-02  1.94444444e-01]]
